# Automatically generated by pb2py
import protobuf as p


class DecredVerifyMessage(p.MessageType):
    FIELDS = {
        1: ('address', p.UnicodeType, 0),
        2: ('signature', p.BytesType, 0),
        3: ('message', p.BytesType, 0),
    }
    MESSAGE_WIRE_TYPE = 119
