# Automatically generated by pb2py
import protobuf as p


class DecredOutPointType(p.MessageType):
    FIELDS = {
        1: ('hash', p.BytesType, 0),  # required
        2: ('index', p.UVarintType, 0),  # required
        3: ('tree', p.BytesType, 0),
    }
